version: 2.1
jobs:
  build:
    filters:
      branches:
        only:
          - main
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run:
          command: |
            git config user.email $EMAIL
            git config user.name $NAME
      - run: npm run webBuild
      - run: npm run addDomain
      - run: yarn deploy
