version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:14
workflows:
  version: 2
  deploy:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - main
jobs:
  publish:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run:
          command: npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      - run:
          command: npx expo publish --non-interactive --max-workers 1
